spring:
  profiles:
    active: test
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver