server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,routes,info

zuul:
  prefix: /api
  routes:
    auth-service:
      sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: "*"

ribbon:
  eager-load:
    enabled: true
  restclient:
    enabled: true