server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health,routes,info