name: Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, test and upload artifact.
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
      
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        
    - 
      name: Build with Maven
      working-directory: ./auth-service
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      
    - 
      name: Test with Maven
      working-directory: ./auth-service
      run: mvn -B test
    
    - 
      name: Create artifact with Maven
      working-directory: ./auth-service
      run: mvn -B clean package --file pom.xml
    - 
      name: Move file
      working-directory: ./auth-service
      run: cp target/*.jar .
    - 
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ./auth-service/
        
  docker:
    name: Download artifact, build docker image and push to registry.
    runs-on: ubuntu-latest
    needs: [build]
    
    steps: 
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
       
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
       
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
          
    - 
      name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        context: ./auth-service
        # Path to the Dockerfile
        file: ./auth-service/Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        tags: jellehuibregste/cah-auth:latest
