name: Client CI

on:
  push:
    branches-ignore: 
      - main
      - release*
    paths:
      - client/**
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '12'
    - run: npm install
      working-directory: ./client
    - run: npm test
      working-directory: ./client
