name: Gateway CI

on:
  push:
    branches-ignore: 
      - main
      - release*
    paths:
      - gateway-service/**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 11
    - name: Build with Maven
      working-directory: ./gateway-service
      run: mvn -B clean package -Dmaven.test.skip=true --file pom.xml
    - name: Test with Maven
      working-directory: ./gateway-service
      run: mvn -B test